### ISSUE TITLE
Captures d'écran

### ISSUE THREAD

**Issue by mehdou92** [esgi-abkhoukh-mehdi/github-discovery#1]
![capture 2](https://user-images.githubusercontent.com/5594086/31616791-eca8f8ac-b28d-11e7-8e71-0d2a045587b8.PNG)
![capture 3](https://user-images.githubusercontent.com/5594086/31616792-ecc97ef6-b28d-11e7-8fa0-3d2e939b678c.PNG)
![capture site](https://user-images.githubusercontent.com/5594086/31616793-ece92b20-b28d-11e7-8d1b-835b068c413b.PNG)
![empty read me](https://user-images.githubusercontent.com/5594086/31616794-ed0a30a4-b28d-11e7-9641-2baabd816cca.PNG)

**Comment by mickaelandrieu** [comment]
Parfait! bon boulot
